<?php

namespace Database\Seeders;

use App\Models\IndustryTemplate;
use Illuminate\Database\Seeder;

class IndustryTemplateSeeder extends Seeder
{
    public function run()
    {
        $templates = [
            [
                'slug' => 'medical-practice',
                'name' => 'Arztpraxis',
                'name_en' => 'Medical Practice',
                'icon' => 'heroicon-o-heart',
                'description' => 'Für Ärzte, Zahnärzte und medizinische Praxen',
                'default_services' => [
                    ['name' => 'Erstberatung', 'duration' => 30, 'price' => 80],
                    ['name' => 'Nachuntersuchung', 'duration' => 15, 'price' => 50],
                    ['name' => 'Vorsorgeuntersuchung', 'duration' => 45, 'price' => 120],
                    ['name' => 'Impfung', 'duration' => 15, 'price' => 40],
                ],
                'default_hours' => [
                    'monday' => ['08:00', '12:00', '14:00', '18:00'],
                    'tuesday' => ['08:00', '12:00', '14:00', '18:00'],
                    'wednesday' => ['08:00', '12:00'],
                    'thursday' => ['08:00', '12:00', '14:00', '18:00'],
                    'friday' => ['08:00', '12:00', '14:00', '17:00'],
                    'saturday' => null,
                    'sunday' => null,
                ],
                'ai_personality' => [
                    'tone' => 'professional',
                    'formality' => 'formal',
                    'empathy_level' => 'high',
                    'greeting' => 'Guten Tag, Sie haben die Praxis {{company_name}} erreicht. Wie kann ich Ihnen helfen?',
                ],
                'common_questions' => [
                    'Haben Sie aktuell freie Termine?',
                    'Benötige ich eine Überweisung?',
                    'Wie lange ist die Wartezeit?',
                    'Welche Krankenkassen werden akzeptiert?',
                ],
                'booking_rules' => [
                    'advance_booking_days' => 60,
                    'min_notice_hours' => 24,
                    'buffer_time' => 5,
                    'emergency_slots' => true,
                ],
                'popularity_score' => 100,
            ],
            [
                'slug' => 'hair-salon',
                'name' => 'Friseursalon',
                'name_en' => 'Hair Salon',
                'icon' => 'heroicon-o-scissors',
                'description' => 'Für Friseure und Beauty-Salons',
                'default_services' => [
                    ['name' => 'Haarschnitt Damen', 'duration' => 45, 'price' => 45],
                    ['name' => 'Haarschnitt Herren', 'duration' => 30, 'price' => 25],
                    ['name' => 'Färben', 'duration' => 120, 'price' => 80],
                    ['name' => 'Dauerwelle', 'duration' => 150, 'price' => 120],
                    ['name' => 'Hochsteckfrisur', 'duration' => 60, 'price' => 60],
                ],
                'default_hours' => [
                    'monday' => null,
                    'tuesday' => ['09:00', '18:00'],
                    'wednesday' => ['09:00', '18:00'],
                    'thursday' => ['09:00', '20:00'],
                    'friday' => ['09:00', '18:00'],
                    'saturday' => ['08:00', '14:00'],
                    'sunday' => null,
                ],
                'ai_personality' => [
                    'tone' => 'friendly',
                    'formality' => 'casual',
                    'empathy_level' => 'medium',
                    'greeting' => 'Hallo! Schön, dass Sie bei {{company_name}} anrufen. Möchten Sie einen Termin vereinbaren?',
                ],
                'common_questions' => [
                    'Wann haben Sie den nächsten freien Termin?',
                    'Was kostet ein Haarschnitt?',
                    'Kann ich auch ohne Termin vorbeikommen?',
                    'Bieten Sie auch Beratung an?',
                ],
                'booking_rules' => [
                    'advance_booking_days' => 30,
                    'min_notice_hours' => 4,
                    'buffer_time' => 0,
                    'walk_ins_allowed' => true,
                ],
                'popularity_score' => 95,
            ],
            [
                'slug' => 'restaurant',
                'name' => 'Restaurant',
                'name_en' => 'Restaurant',
                'icon' => 'heroicon-o-cake',
                'description' => 'Für Restaurants und Gastronomie',
                'default_services' => [
                    ['name' => 'Tischreservierung 2 Personen', 'duration' => 120, 'price' => 0],
                    ['name' => 'Tischreservierung 4 Personen', 'duration' => 120, 'price' => 0],
                    ['name' => 'Tischreservierung 6+ Personen', 'duration' => 150, 'price' => 0],
                    ['name' => 'Private Feier', 'duration' => 240, 'price' => 0],
                ],
                'default_hours' => [
                    'monday' => ['11:30', '14:30', '17:30', '22:00'],
                    'tuesday' => ['11:30', '14:30', '17:30', '22:00'],
                    'wednesday' => ['11:30', '14:30', '17:30', '22:00'],
                    'thursday' => ['11:30', '14:30', '17:30', '22:00'],
                    'friday' => ['11:30', '14:30', '17:30', '23:00'],
                    'saturday' => ['11:30', '23:00'],
                    'sunday' => ['11:30', '22:00'],
                ],
                'ai_personality' => [
                    'tone' => 'warm',
                    'formality' => 'semi-formal',
                    'empathy_level' => 'medium',
                    'greeting' => 'Herzlich willkommen bei {{company_name}}! Möchten Sie einen Tisch reservieren?',
                ],
                'common_questions' => [
                    'Haben Sie heute Abend noch einen Tisch frei?',
                    'Gibt es vegetarische Gerichte?',
                    'Kann man bei Ihnen auch feiern?',
                    'Haben Sie eine Terrasse?',
                ],
                'booking_rules' => [
                    'advance_booking_days' => 90,
                    'min_notice_hours' => 2,
                    'buffer_time' => 15,
                    'max_party_size' => 20,
                ],
                'popularity_score' => 90,
            ],
            [
                'slug' => 'law-firm',
                'name' => 'Anwaltskanzlei',
                'name_en' => 'Law Firm',
                'icon' => 'heroicon-o-scale',
                'description' => 'Für Anwälte und Rechtsberatung',
                'default_services' => [
                    ['name' => 'Erstberatung', 'duration' => 60, 'price' => 250],
                    ['name' => 'Vertragsberatung', 'duration' => 90, 'price' => 350],
                    ['name' => 'Gerichtstermin Vorbereitung', 'duration' => 120, 'price' => 500],
                    ['name' => 'Telefonberatung', 'duration' => 30, 'price' => 150],
                ],
                'default_hours' => [
                    'monday' => ['09:00', '17:00'],
                    'tuesday' => ['09:00', '17:00'],
                    'wednesday' => ['09:00', '17:00'],
                    'thursday' => ['09:00', '17:00'],
                    'friday' => ['09:00', '15:00'],
                    'saturday' => null,
                    'sunday' => null,
                ],
                'ai_personality' => [
                    'tone' => 'professional',
                    'formality' => 'very_formal',
                    'empathy_level' => 'low',
                    'greeting' => 'Guten Tag, Sie sprechen mit der Kanzlei {{company_name}}. Wie darf ich Ihnen behilflich sein?',
                ],
                'common_questions' => [
                    'Welche Rechtsgebiete decken Sie ab?',
                    'Was kostet eine Erstberatung?',
                    'Wie schnell kann ich einen Termin bekommen?',
                    'Bieten Sie auch Rechtsschutz an?',
                ],
                'booking_rules' => [
                    'advance_booking_days' => 30,
                    'min_notice_hours' => 24,
                    'buffer_time' => 15,
                    'require_case_description' => true,
                ],
                'popularity_score' => 70,
            ],
            [
                'slug' => 'auto-repair',
                'name' => 'Autowerkstatt',
                'name_en' => 'Auto Repair Shop',
                'icon' => 'heroicon-o-wrench-screwdriver',
                'description' => 'Für KFZ-Werkstätten und Reifenservice',
                'default_services' => [
                    ['name' => 'Inspektion', 'duration' => 90, 'price' => 150],
                    ['name' => 'Ölwechsel', 'duration' => 30, 'price' => 60],
                    ['name' => 'Reifenwechsel', 'duration' => 45, 'price' => 40],
                    ['name' => 'HU/AU', 'duration' => 60, 'price' => 120],
                    ['name' => 'Diagnose', 'duration' => 30, 'price' => 50],
                ],
                'default_hours' => [
                    'monday' => ['08:00', '17:00'],
                    'tuesday' => ['08:00', '17:00'],
                    'wednesday' => ['08:00', '17:00'],
                    'thursday' => ['08:00', '17:00'],
                    'friday' => ['08:00', '16:00'],
                    'saturday' => ['09:00', '13:00'],
                    'sunday' => null,
                ],
                'ai_personality' => [
                    'tone' => 'helpful',
                    'formality' => 'casual',
                    'empathy_level' => 'medium',
                    'greeting' => 'Guten Tag! {{company_name}} hier. Was kann ich für Sie und Ihr Fahrzeug tun?',
                ],
                'common_questions' => [
                    'Wann kann ich zur Inspektion kommen?',
                    'Was kostet ein Reifenwechsel?',
                    'Machen Sie auch TÜV?',
                    'Haben Sie Leihwagen?',
                ],
                'booking_rules' => [
                    'advance_booking_days' => 14,
                    'min_notice_hours' => 4,
                    'buffer_time' => 0,
                    'require_car_details' => true,
                ],
                'popularity_score' => 85,
            ],
            [
                'slug' => 'fitness-studio',
                'name' => 'Fitnessstudio',
                'name_en' => 'Fitness Studio',
                'icon' => 'heroicon-o-trophy',
                'description' => 'Für Fitnessstudios und Personal Trainer',
                'default_services' => [
                    ['name' => 'Probetraining', 'duration' => 60, 'price' => 0],
                    ['name' => 'Personal Training', 'duration' => 60, 'price' => 80],
                    ['name' => 'Ernährungsberatung', 'duration' => 45, 'price' => 60],
                    ['name' => 'Fitness-Check', 'duration' => 30, 'price' => 40],
                ],
                'default_hours' => [
                    'monday' => ['06:00', '22:00'],
                    'tuesday' => ['06:00', '22:00'],
                    'wednesday' => ['06:00', '22:00'],
                    'thursday' => ['06:00', '22:00'],
                    'friday' => ['06:00', '22:00'],
                    'saturday' => ['08:00', '20:00'],
                    'sunday' => ['09:00', '20:00'],
                ],
                'ai_personality' => [
                    'tone' => 'energetic',
                    'formality' => 'casual',
                    'empathy_level' => 'high',
                    'greeting' => 'Hey! Super, dass du bei {{company_name}} anrufst! Wie können wir dir zu deinen Fitnesszielen verhelfen?',
                ],
                'common_questions' => [
                    'Was kostet eine Mitgliedschaft?',
                    'Kann ich ein Probetraining machen?',
                    'Habt ihr auch Kurse?',
                    'Gibt es Studentenrabatt?',
                ],
                'booking_rules' => [
                    'advance_booking_days' => 7,
                    'min_notice_hours' => 2,
                    'buffer_time' => 0,
                    'trial_session_limit' => 1,
                ],
                'popularity_score' => 75,
            ],
            [
                'slug' => 'dental-practice',
                'name' => 'Zahnarztpraxis',
                'name_en' => 'Dental Practice',
                'icon' => 'heroicon-o-face-smile',
                'description' => 'Für Zahnärzte und Kieferorthopäden',
                'default_services' => [
                    ['name' => 'Kontrolluntersuchung', 'duration' => 30, 'price' => 60],
                    ['name' => 'Zahnreinigung', 'duration' => 60, 'price' => 120],
                    ['name' => 'Füllung', 'duration' => 45, 'price' => 150],
                    ['name' => 'Notfalltermin', 'duration' => 30, 'price' => 100],
                ],
                'default_hours' => [
                    'monday' => ['08:00', '12:00', '14:00', '18:00'],
                    'tuesday' => ['08:00', '12:00', '14:00', '20:00'],
                    'wednesday' => ['08:00', '14:00'],
                    'thursday' => ['08:00', '12:00', '14:00', '18:00'],
                    'friday' => ['08:00', '14:00'],
                    'saturday' => null,
                    'sunday' => null,
                ],
                'ai_personality' => [
                    'tone' => 'calming',
                    'formality' => 'formal',
                    'empathy_level' => 'very_high',
                    'greeting' => 'Guten Tag, hier ist die Zahnarztpraxis {{company_name}}. Wie kann ich Ihnen helfen?',
                ],
                'common_questions' => [
                    'Ich habe Zahnschmerzen, wann kann ich kommen?',
                    'Was kostet eine Zahnreinigung?',
                    'Behandeln Sie auch Angstpatienten?',
                    'Nehmen Sie neue Patienten auf?',
                ],
                'booking_rules' => [
                    'advance_booking_days' => 90,
                    'min_notice_hours' => 24,
                    'buffer_time' => 5,
                    'emergency_slots' => true,
                ],
                'popularity_score' => 88,
            ],
            [
                'slug' => 'real-estate',
                'name' => 'Immobilienmakler',
                'name_en' => 'Real Estate Agency',
                'icon' => 'heroicon-o-home',
                'description' => 'Für Immobilienmakler und -verwalter',
                'default_services' => [
                    ['name' => 'Besichtigungstermin', 'duration' => 45, 'price' => 0],
                    ['name' => 'Beratungsgespräch Verkauf', 'duration' => 60, 'price' => 0],
                    ['name' => 'Beratungsgespräch Kauf', 'duration' => 60, 'price' => 0],
                    ['name' => 'Objektbewertung', 'duration' => 90, 'price' => 0],
                ],
                'default_hours' => [
                    'monday' => ['09:00', '18:00'],
                    'tuesday' => ['09:00', '18:00'],
                    'wednesday' => ['09:00', '18:00'],
                    'thursday' => ['09:00', '18:00'],
                    'friday' => ['09:00', '17:00'],
                    'saturday' => ['10:00', '14:00'],
                    'sunday' => null,
                ],
                'ai_personality' => [
                    'tone' => 'professional',
                    'formality' => 'semi-formal',
                    'empathy_level' => 'medium',
                    'greeting' => 'Herzlich willkommen bei {{company_name}} Immobilien. Suchen Sie eine Immobilie oder möchten Sie verkaufen?',
                ],
                'common_questions' => [
                    'Welche Objekte haben Sie im Angebot?',
                    'Was kostet Ihre Dienstleistung?',
                    'Können Sie meine Immobilie bewerten?',
                    'Wann können wir eine Besichtigung machen?',
                ],
                'booking_rules' => [
                    'advance_booking_days' => 14,
                    'min_notice_hours' => 24,
                    'buffer_time' => 30,
                    'travel_time_included' => true,
                ],
                'popularity_score' => 65,
            ],
            [
                'slug' => 'veterinary',
                'name' => 'Tierarztpraxis',
                'name_en' => 'Veterinary Clinic',
                'icon' => 'heroicon-o-heart',
                'description' => 'Für Tierärzte und Tierkliniken',
                'default_services' => [
                    ['name' => 'Allgemeine Untersuchung', 'duration' => 30, 'price' => 50],
                    ['name' => 'Impfung', 'duration' => 20, 'price' => 60],
                    ['name' => 'Kastration', 'duration' => 60, 'price' => 200],
                    ['name' => 'Notfall', 'duration' => 45, 'price' => 150],
                ],
                'default_hours' => [
                    'monday' => ['08:00', '12:00', '14:00', '18:00'],
                    'tuesday' => ['08:00', '12:00', '14:00', '18:00'],
                    'wednesday' => ['08:00', '12:00', '14:00', '18:00'],
                    'thursday' => ['08:00', '12:00', '14:00', '18:00'],
                    'friday' => ['08:00', '12:00', '14:00', '18:00'],
                    'saturday' => ['09:00', '12:00'],
                    'sunday' => null,
                ],
                'ai_personality' => [
                    'tone' => 'caring',
                    'formality' => 'semi-formal',
                    'empathy_level' => 'very_high',
                    'greeting' => 'Guten Tag, Tierarztpraxis {{company_name}}. Wie geht es Ihrem Liebling?',
                ],
                'common_questions' => [
                    'Mein Tier hat ein Problem, wann können wir kommen?',
                    'Was kostet eine Impfung?',
                    'Haben Sie auch am Wochenende auf?',
                    'Behandeln Sie auch exotische Tiere?',
                ],
                'booking_rules' => [
                    'advance_booking_days' => 30,
                    'min_notice_hours' => 4,
                    'buffer_time' => 5,
                    'emergency_slots' => true,
                ],
                'popularity_score' => 82,
            ],
            [
                'slug' => 'beauty-spa',
                'name' => 'Kosmetikstudio',
                'name_en' => 'Beauty Spa',
                'icon' => 'heroicon-o-sparkles',
                'description' => 'Für Kosmetikstudios und Wellness',
                'default_services' => [
                    ['name' => 'Gesichtsbehandlung', 'duration' => 60, 'price' => 80],
                    ['name' => 'Maniküre', 'duration' => 45, 'price' => 40],
                    ['name' => 'Pediküre', 'duration' => 60, 'price' => 50],
                    ['name' => 'Wimpernverlängerung', 'duration' => 120, 'price' => 120],
                    ['name' => 'Massage', 'duration' => 60, 'price' => 70],
                ],
                'default_hours' => [
                    'monday' => ['10:00', '19:00'],
                    'tuesday' => ['10:00', '19:00'],
                    'wednesday' => ['10:00', '19:00'],
                    'thursday' => ['10:00', '20:00'],
                    'friday' => ['10:00', '19:00'],
                    'saturday' => ['09:00', '16:00'],
                    'sunday' => null,
                ],
                'ai_personality' => [
                    'tone' => 'relaxing',
                    'formality' => 'casual',
                    'empathy_level' => 'high',
                    'greeting' => 'Willkommen bei {{company_name}}! Möchten Sie sich heute etwas Gutes tun?',
                ],
                'common_questions' => [
                    'Was bieten Sie alles an?',
                    'Haben Sie heute noch einen Termin frei?',
                    'Was kostet eine Gesichtsbehandlung?',
                    'Kann ich auch einen Gutschein kaufen?',
                ],
                'booking_rules' => [
                    'advance_booking_days' => 60,
                    'min_notice_hours' => 24,
                    'buffer_time' => 15,
                    'package_deals' => true,
                ],
                'popularity_score' => 78,
            ],
        ];

        foreach ($templates as $template) {
            IndustryTemplate::create($template);
        }
    }
}