<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\AuthServiceProvider::class,
    App\Providers\BroadcastServiceProvider::class,
    App\Providers\CalcomMigrationServiceProvider::class,
    App\Providers\CircuitBreakerServiceProvider::class,
    App\Providers\DatabaseServiceProvider::class,
    App\Providers\DatabasePoolServiceProvider::class,
    App\Providers\EventServiceProvider::class,
    App\Providers\FortifyServiceProvider::class,
    App\Providers\FilamentBadgeServiceProvider::class,
    App\Providers\FilamentSafeFixesServiceProvider::class,
    App\Providers\Filament\AdminPanelProvider::class,
    App\Providers\GdprServiceProvider::class,
    App\Providers\HorizonServiceProvider::class,
    App\Providers\KnowledgeServiceProvider::class,
    App\Providers\LockingServiceProvider::class,
    App\Providers\LoggingServiceProvider::class,
    App\Providers\MCPServiceProvider::class,
    App\Providers\MonitoringServiceProvider::class,
    App\Providers\PerformanceServiceProvider::class,
    App\Providers\RouteServiceProvider::class,
    App\Providers\ServiceTrackingProvider::class,
    App\Providers\ValidationServiceProvider::class,
];
