#!/bin/bash
# Monitoring Commands for 2025-10-25 Deployment
# Auto-generated by Claude Code

echo "=== Daily Deployment Monitoring ==="
echo ""

# Bug #2: German Weekday Parsing
echo "1. Bug #2 - German Weekday Reschedules:"
grep -c "V10.*parseDateString.*Montag\|Dienstag\|Mittwoch\|Donnerstag\|Freitag\|Samstag\|Sonntag" storage/logs/laravel-$(date +%Y-%m-%d).log 2>/dev/null || echo "0"

# Bug #3: ICS Email Generation
echo "2. Bug #3 - ICS Emails Sent:"
grep -c "ICS.*generated successfully\|Email sent" storage/logs/laravel-$(date +%Y-%m-%d).log 2>/dev/null || echo "0"

# Bug #11: Booking Notice Validation
echo "3. Bug #11 - Booking Notice Blocks (<15min):"
grep -c "Booking notice validation.*failed" storage/logs/laravel-$(date +%Y-%m-%d).log 2>/dev/null || echo "0"

# Bug #10: Service Selection Pinning
echo "4. Bug #10 - Service Pinning Events:"
grep -c "Service pinned.*for call\|Service selection" storage/logs/laravel-$(date +%Y-%m-%d).log 2>/dev/null || echo "0"

# Policy System
echo "5. Policy System - Anonymous Blocks:"
grep -c "Anonymous caller tried\|Policy violation" storage/logs/laravel-$(date +%Y-%m-%d).log 2>/dev/null || echo "0"

echo ""
echo "✅ Monitoring check complete"
