global:
  resolve_timeout: 5m
  smtp_from: 'alerts@askproai.de'
  smtp_smarthost: 'smtp.example.com:587'
  smtp_auth_username: 'alerts@askproai.de'
  smtp_auth_password: 'YOUR_SMTP_PASSWORD'
  slack_api_url: 'YOUR_SLACK_WEBHOOK_URL'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'team-critical'
  routes:
  - match:
      severity: critical
    receiver: team-critical
    continue: true
  - match:
      severity: warning
    receiver: team-warning
  - match:
      service: stripe
    receiver: team-payments
  - match:
      service: security
    receiver: team-security

receivers:
- name: 'team-critical'
  email_configs:
  - to: 'critical@askproai.de'
    headers:
      Subject: '[CRITICAL] {{ .GroupLabels.alertname }} - AskProAI Production Alert'
    html: '{{ template "email.default.html" . }}'
  slack_configs:
  - channel: '#alerts-critical'
    title: 'CRITICAL: {{ .GroupLabels.alertname }}'
    text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    send_resolved: true
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
  pagerduty_configs:
  - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
    description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'

- name: 'team-warning'
  email_configs:
  - to: 'ops@askproai.de'
    headers:
      Subject: '[WARNING] {{ .GroupLabels.alertname }} - AskProAI Alert'
  slack_configs:
  - channel: '#alerts-warning'
    title: 'Warning: {{ .GroupLabels.alertname }}'
    send_resolved: true

- name: 'team-payments'
  email_configs:
  - to: 'payments@askproai.de'
    headers:
      Subject: '[PAYMENT] {{ .GroupLabels.alertname }} - Stripe Alert'
  slack_configs:
  - channel: '#alerts-payments'
    title: 'Payment Alert: {{ .GroupLabels.alertname }}'
    send_resolved: true

- name: 'team-security'
  email_configs:
  - to: 'security@askproai.de'
    headers:
      Subject: '[SECURITY] {{ .GroupLabels.alertname }} - Security Alert'
  slack_configs:
  - channel: '#alerts-security'
    title: 'SECURITY ALERT: {{ .GroupLabels.alertname }}'
    color: 'danger'
    send_resolved: false

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']