#!/bin/bash

# 500 Error Prevention Script
# Generated by /sc:troubleshoot
# Prevents common causes of 500 errors

set -e

echo "🛡️ 500 Error Prevention Check"
echo "=============================="
echo ""

ERRORS=0

# 1. Check PHP Memory Limit
echo -n "✓ PHP Memory Limit... "
MEM_LIMIT=$(grep "memory_limit" /etc/php/8.3/fpm/pool.d/www.conf | grep -v "^;" | tail -1 | cut -d'=' -f2 | tr -d ' ')
if [[ "$MEM_LIMIT" == *"G"* ]]; then
    echo "❌ WARNING: $MEM_LIMIT is too high!"
    ERRORS=$((ERRORS + 1))
else
    echo "✅ $MEM_LIMIT"
fi

# 2. Check Database Connection
echo -n "✓ Database Connection... "
if php artisan tinker --execute="DB::connection()->getPdo();" > /dev/null 2>&1; then
    echo "✅ Connected"
else
    echo "❌ FAILED"
    ERRORS=$((ERRORS + 1))
fi

# 3. Check for Duplicate Resource Files
echo -n "✓ Duplicate Resource Files... "
DUPLICATES=$(find /var/www/api-gateway/app/Filament/Resources -name "*Optimized.php" 2>/dev/null | wc -l)
if [ "$DUPLICATES" -gt 0 ]; then
    echo "❌ Found $DUPLICATES duplicate files"
    ERRORS=$((ERRORS + 1))
else
    echo "✅ None found"
fi

# 4. Check Calls Table Indexes
echo -n "✓ Calls Table Indexes... "
INDEX_COUNT=$(php artisan tinker --execute="echo count(DB::select('SHOW INDEX FROM calls'));" 2>/dev/null)
if [ "$INDEX_COUNT" -gt 64 ]; then
    echo "❌ $INDEX_COUNT indexes (max 64)"
    ERRORS=$((ERRORS + 1))
else
    echo "✅ $INDEX_COUNT indexes"
fi

# 5. Check Service Status
echo -n "✓ PHP-FPM Status... "
if systemctl is-active php8.3-fpm > /dev/null; then
    echo "✅ Running"
else
    echo "❌ Not running"
    ERRORS=$((ERRORS + 1))
fi

echo -n "✓ MariaDB Status... "
if systemctl is-active mariadb > /dev/null; then
    echo "✅ Running"
else
    echo "❌ Not running"
    ERRORS=$((ERRORS + 1))
fi

# 6. Check Disk Space
echo -n "✓ Disk Space... "
DISK_USAGE=$(df / | tail -1 | awk '{print $5}' | tr -d '%')
if [ "$DISK_USAGE" -gt 90 ]; then
    echo "❌ ${DISK_USAGE}% used (critical)"
    ERRORS=$((ERRORS + 1))
else
    echo "✅ ${DISK_USAGE}% used"
fi

# 7. Check Error Logs
echo -n "✓ Recent Errors... "
ERROR_COUNT=$(tail -100 /var/www/api-gateway/storage/logs/laravel.log | grep -c "ERROR" || true)
if [ "$ERROR_COUNT" -gt 10 ]; then
    echo "❌ $ERROR_COUNT errors in last 100 lines"
    ERRORS=$((ERRORS + 1))
else
    echo "✅ $ERROR_COUNT errors"
fi

# Summary
echo ""
echo "=============================="
if [ "$ERRORS" -eq 0 ]; then
    echo "✅ All checks passed! System healthy."
else
    echo "⚠️ Found $ERRORS potential issues!"
    echo ""
    echo "Recommended actions:"
    [ "$INDEX_COUNT" -gt 64 ] && echo "  • Run: php /var/www/api-gateway/scripts/cleanup-calls-indexes.php"
    [ "$DUPLICATES" -gt 0 ] && echo "  • Run: rm /var/www/api-gateway/app/Filament/Resources/*Optimized.php"
    [ "$DISK_USAGE" -gt 90 ] && echo "  • Clear logs: truncate -s 0 /var/www/api-gateway/storage/logs/*.log"
fi

exit $ERRORS