global:
  resolve_timeout: 5m
  smtp_from: 'alerts@askproai.de'
  smtp_smarthost: 'smtp.udag.de:587'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: critical
      continue: true
    - match:
        severity: warning
      receiver: warning

receivers:
  - name: 'default'
    email_configs:
      - to: 'devops@askproai.de'
        headers:
          Subject: '[AskProAI] Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h2>{{ .GroupLabels.alertname }}</h2>
          <p><b>Severity:</b> {{ .CommonLabels.severity }}</p>
          <p><b>Service:</b> {{ .CommonLabels.service }}</p>
          {{ range .Alerts }}
          <hr>
          <p><b>Summary:</b> {{ .Annotations.summary }}</p>
          <p><b>Description:</b> {{ .Annotations.description }}</p>
          <p><b>Started:</b> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
          {{ end }}

  - name: 'critical'
    email_configs:
      - to: 'oncall@askproai.de'
        headers:
          Subject: '[CRITICAL] AskProAI Alert: {{ .GroupLabels.alertname }}'
    webhook_configs:
      - url: '${SLACK_WEBHOOK_CRITICAL}'
        send_resolved: true

  - name: 'warning'
    email_configs:
      - to: 'devops@askproai.de'
        headers:
          Subject: '[WARNING] AskProAI Alert: {{ .GroupLabels.alertname }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']