name: static-analysis
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.3', tools: composer }
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/pint --test
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.3', tools: composer }
      - run: composer install --no-interaction --prefer-dist
      - name: Debug PHPStan config
        run: |
          echo "=== PHPStan config files ==="
          ls -la phpstan*
          echo "=== PHPStan.neon content ==="
          cat phpstan.neon || true
          echo "=== Baseline first 10 lines ==="
          head -10 phpstan-baseline.neon || true
      - name: Run PHPStan with explicit config
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=1G --configuration=phpstan.neon
